apiVersion: v1
kind: Endpoints
metadata:
  name: prom-kube-scheduler
  namespace: kube-system
  labels:
    app: kube-prometheus-stack-kube-scheduler
    jobLabel: kube-scheduler
    release: prometheus-stack
subsets:
  - addresses:
      - ip: 192.168.45.123
    ports:
      - name: http-metrics
        port: 10259
        protocol: TCP
