apiVersion: v1
kind: Endpoints
metadata:
  name: prom-kube-etcd
  namespace: kube-system
  labels:
    app: kube-prometheus-stack-kube-etcd
    jobLabel: kube-etcd
    release: prometheus-stack
subsets:
  - addresses:
      - ip: 192.168.45.123
    ports:
      - name: http-metrics
        port: 2381
        protocol: TCP
